### PR TITLE
Use EveryDict instead of List of Tuples

### PR DESCRIPTION
**Pull request by fendor**
Because of Elm's rather weird situation with `comparable`, the `Dict` in the core library can not take arbitrary types as a key.

This raises the inconvenience to substitute data structures with a non-comparable type, to be rewritten to the following form `List ( k, v )` where `k` is the key and `v` the value. This can cause a performance issue on large data-sets and also inconvenient access-functions which have to be defined by the programmer. 

For this reason, my fork solves this problem by declaring an additional dependency on the [elm-all-dict](http://package.elm-lang.org/packages/eeue56/elm-all-dict/2.0.1)-library and replacing all occurrences of the form `List ( k, v )` and `Dict comparable v` to `EveryDict k v`.

The tests have been updated and run, and the fork is currently used in a project without a problem, but I think some use-cases have not been tested yet.

I also defined own function for decoding and encoding `EveryDict` which are based on the functions `encodeMap` and `decodeMap` from [json-helpers](http://package.elm-lang.org/packages/bartavelle/json-helpers/1.3.0/Json-Helpers).

### CODE REVIEW

**Comment by bartavelle** [comment]
I don't think it is acceptable to impose an additional constraint by default. However, I *think* it might be possible to design a custom [alteration](https://github.com/agrafix/elm-bridge/blob/646a2a3f721d7f885d53e730510188fd9c8b9002/src/Elm/Module.hs#L105-L127) that would use that `EveryDict` module. That might make it really easy to support both plain `Dict` for those who don't care or don't have the performance problem, and those who need `EveryDict`.

**Comment by fendor** [comment]
You mean, an additional derive option? For example:

```haskell
-- | Note that This default set of options is distinct from that in
-- the @aeson@ package.
defaultOptions :: A.Options
defaultOptions
  = A.defaultOptions
  { {- ommit other fields for clarity -}
  ...
  , A.useEveryDict            = False
  }

```

But I think this would require an additional argument to `makeElmModuleWithVersion`

**Comment by bartavelle** [comment]
No, I mean the first argument to `makeModuleContentWithAlterations`.

**Comment by fendor** [comment]
Yes, but how can a programmer specify to use alteration?

**Comment by fendor** [comment]
*another alteration

**Comment by fendor** [comment]
OK, I think I understand what you mean, I will look into it later and squash these comments, sorry, it was not possible to edit these from phone

**Comment by fendor** [comment]
I have currently no intention on working on this, thus I am closing the PR.

**Pull request closed without merging**
