### PR TITLE
Support GHC 9.8 - as well as older ghc

### PR DESCRIPTION
**Pull request by runebak**
Make tuples work on older ghc as well in pull request
https://github.com/agrafix/elm-bridge/pull/60

### CODE REVIEW

**Comment by runebak** [comment]
Any news on this? It would be great to depend on the official hackage version instead of my own github version.

**Comment by bartavelle** [comment]
Pushed 0.8.4 on cabal.

**Comment by runebak** [comment]
Thanks! The changelog doesn't say anything, should I have wrote something there? Anyway, it works now - great!

**Comment by runebak** [comment]
Thank you for the heads up. Would you suggest moving to another package for elm client code generation? I chose servant-elm as this package is in the the haskell-servant repo, so I thought it was the most well maintained, but that might not be the case.

**Pull request merged**
