### PR TITLE
Support GHC 9.8

### PR DESCRIPTION
**Pull request by ilyakooo0**

### CODE REVIEW

**Comment by bartavelle** [comment]
Thanks! I see there is a tuple fix, but does it work with previous versions of GHC?

**Comment by ilyakooo0** [comment]
No, it doesn't, Tuples will be broken.

**Comment by bartavelle** [comment]
Then it would be helpful to fence that in CPP blocks. Would you mind doing that?

**Comment by bartavelle** [comment]
This PR only works on the latest GHC and breaks with other versions, it needs some work before it can be accepted :(

**Comment by ilyakooo0** [comment]
I am currently time constrained and don't know when I will have time to work on this. Feel free to fork this PR if you need this done urgently.

**Comment by runebak** [comment]
I don't know how to update this pull-request, but I forked the repo of the pull-request and made the new pull-request there. I just doubled the check for the two types of tuples for the different version of ghc. Found that simpler than any CPP-checks. But let me know if you think otherwise.

**Comment by bartavelle** [comment]
Where is the new code?

**Comment by ilyakooo0** [comment]
@runebak you probably want to create a second PR. I will close this one once you create yours.

**Comment by runebak** [comment]
I made the pull request on the forked repo, now I made a new one here https://github.com/agrafix/elm-bridge/pull/62 instead
Sorry, I'm new at pull requesting on github!

**Pull request merged**
