### PR TITLE
Make decoder for sum types use 'lazy' combinator to allow recursive types

### PR DESCRIPTION
**Pull request by Saulzar**
Here's the change using 'lazy', I guess the only potential issue is performance, given the decoder is now a function it'll get recreated over and over. It does generate code which is accepted by Elm.

Same example as before:

```
jsonDecEdit : Json.Decode.Decoder ( Edit )
jsonDecEdit =
    let jsonDecDictEdit = Dict.fromList
            [ ("Add", Json.Decode.lazy (\_ -> Json.Decode.map2 Add (Json.Decode.index 0 (Json.Decode.int)) (Json.Decode.index 1 (jsonDecObject))))
            , ("Delete", Json.Decode.lazy (\_ -> Json.Decode.map Delete (Json.Decode.int)))
            , ("Transform", Json.Decode.lazy (\_ -> Json.Decode.map3 Transform (Json.Decode.index 0 (Json.Decode.list (Json.Decode.int))) (Json.Decode.index 1 (Json.Decode.float)) (Json.Decode.index 2 (jsonDecVec2))))
            , ("Many", Json.Decode.lazy (\_ -> Json.Decode.map Many (Json.Decode.list (jsonDecEdit))))
            ]
    in  decodeSumObjectWithSingleField  "Edit" jsonDecDictEdit
```

### CODE REVIEW

**Comment by bartavelle** [comment]
You will have to fix the tests. As for the performance impact, I suppose it would be negligible for most users, but it might be useful to make it optional for some use cases. I can do the optional part later when needed.

**Comment by Saulzar** [comment]
I'm not sure what's up with the tests, the failing part seems to have nothing to do with this pull request:

> ghc: could not execute: hspec-discover

**Comment by bartavelle** [comment]
Yeah, this is broken for some reason. However, the tests are certainly failing anyway :)

**Comment by Saulzar** [comment]
Looks like it's as simple as missing hspec-discover on the travis script probably. The tests picked up that I'd missed out the record sum case :)

**Comment by bartavelle** [comment]
Cool! I'll merge this and test it a bit before releasing.

**Pull request merged**
